### ISSUE TITLE
[BUG] ...

### ISSUE THREAD

**Issue by M1chal179** [RCVolus/league-observer-tool#24] opened 2023-10-10 20:51 UTC
Hello iam running windows 10 and use league observer tool but sometimes it randomly crash during stream which is ba

**Comment by sdomi4** [comment] 2023-10-10 20:52
Duplicate of #21

**Closed** 2023-10-10 20:52 UTC
Labels: bug

**Comment by M1chal179** [comment] 2023-10-10 20:55
why u closed it ?

**Comment by sdomi4** [comment] 2023-10-10 20:55
because we are tracking the observer tool crashes in #21

**Comment by M1chal179** [comment] 2023-10-10 20:57
should i install now older version to not crash or ?

**Comment by M1chal179** [comment] 2023-10-10 20:57
and last question can i get ban for using farsight ?

**Comment by sdomi4** [comment] 2023-10-10 21:00
No, there isn't currently any older version you can install that is stable.
Currently, Farsight is allowed by Riot, but this stance might change in the future.
