### ISSUE TITLE
Farsight swapping between "Standby" and "Sync" every ~second

### ISSUE THREAD

**Issue by Ainvyy** [RCVolus/league-observer-tool#9] opened 2023-03-26 14:44 UTC
I am having Problems with Farsight, it flashes between Standby and Sync, everything else is working fine. Even when its not connected to LCU & Server it is still doing the same thing. It starts before LiveEventsor Ingame is synced. After quitting pectate I get an Error Message
![ErrMSG](https://user-images.githubusercontent.com/108176325/227783416-28219dbe-08c7-4f11-ae86-a4f27544f903.PNG)
 I accepted the Pop-up with the Memory warning, did I need to setup anything else for Farsight to work?

**Comment by Jadiac5** [comment] 2023-03-27 22:01
Have the same issue.
is this also the reason the new overlay's timer and stat updates don't work? I guess they are based on the farsight info?

**Comment by brunogracco** [comment] 2023-03-31 13:33
i'm having the same issue, is there a fix for this overlay's timer and stat not updating problem ?

**Comment by FireFoXz09** [comment] 2023-04-01 00:51
Same issue here. Tried a full clean install of the Toolkit and the Observer Tool to be sure.

**Comment by figyl** [comment] 2023-04-04 19:40
The native farsight modulel had an update recently that should fix it, i guess that requires a new release for the Observer Tool.

**Comment by Himyu** [comment] 2023-04-04 20:31
Farsight swapping between "Standby" and "Sync" was/is due to how farsight works and means it is not working correctly, after the newest update to the farsight module and therefore also an update to the observer tool this issue should be fixed. Please feel free to test it and come back to us.

**Comment by figyl** [comment] 2023-04-04 21:24
Works as intended now!
Thanks for the release!

**Closed** 2023-04-04 21:25 UTC
Labels: bug
